# Spring properties
spring:
  application:
    name: producer-service

server:
  port: 8089 #Change me, and start another instance ;)

# Discovery Server Access
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${server.port}
      preferIpAddress: true
ribbon:
  eureka:
    enabled: true