# Spring properties
spring:
  application:
    name: consumer-service

server:
  port: 8080 #Change me, and start another instance ;)

# Discovery Server Access
eureka:
  client:
      healthcheck:
        enabled: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  instance:
    metadataMap:
      instanceId: ${server.port}
      statusPageUrlPath: ${management.context-path}/info
      healthCheckUrlPath: ${management.context-path}/health
ribbon:
  eureka:
    enabled: true